allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    configurations.all {
        resolutionStrategy {
            force 'androidx.activity:activity:1.10.1'
            force 'androidx.activity:activity-ktx:1.10.1'
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
