// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBFxwS0P8MyMI1sWPAZj-MGpJgIDypru4',
    appId: '1:187989256881:web:fdaa37bf3ea603d9bc1090',
    messagingSenderId: '187989256881',
    projectId: 'muserpol-pvt-9d002',
    authDomain: 'muserpol-pvt-9d002.firebaseapp.com',
    storageBucket: 'muserpol-pvt-9d002.appspot.com',
    measurementId: 'G-N1N1LG0V44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsJsAW_S_1yX5e3pqbVw-a36miLjUZYCA',
    appId: '1:187989256881:android:1cd5c7a80bf19837bc1090',
    messagingSenderId: '187989256881',
    projectId: 'muserpol-pvt-9d002',
    storageBucket: 'muserpol-pvt-9d002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJR6tDPrhJMz7ASR3OXt3aishuZfL8qA',
    appId: '1:187989256881:ios:78d987f4ac6fe31bbc1090',
    messagingSenderId: '187989256881',
    projectId: 'muserpol-pvt-9d002',
    storageBucket: 'muserpol-pvt-9d002.appspot.com',
    androidClientId: '187989256881-dkukight1kccbb3mh4uchrib1tqvnqsm.apps.googleusercontent.com',
    iosClientId: '187989256881-5npl5h1orh1gkkasc63psiog1bkiakai.apps.googleusercontent.com',
    iosBundleId: 'com.muserpol.pvtmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJR6tDPrhJMz7ASR3OXt3aishuZfL8qA',
    appId: '1:187989256881:ios:97d7442b1f3eddf7bc1090',
    messagingSenderId: '187989256881',
    projectId: 'muserpol-pvt-9d002',
    storageBucket: 'muserpol-pvt-9d002.appspot.com',
    androidClientId: '187989256881-dkukight1kccbb3mh4uchrib1tqvnqsm.apps.googleusercontent.com',
    iosClientId: '187989256881-qkg1ep5ie8rarc3pc5jcmpj79v362fm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.muserpolPvt',
  );
}
